#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        if command -v cygpath > /dev/null 2>&1; then
            basedir=`cygpath -w "$basedir"`
        fi
    ;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/home/joelsgc/wall-e/rpi/~/.local/share/pnpm/global/5/.pnpm/tsx@4.22.3/node_modules/tsx/node_modules:/home/joelsgc/wall-e/rpi/~/.local/share/pnpm/global/5/.pnpm/tsx@4.22.3/node_modules:~/.local/share/pnpm/global/5/.pnpm/node_modules"
else
  export NODE_PATH="/home/joelsgc/wall-e/rpi/~/.local/share/pnpm/global/5/.pnpm/tsx@4.22.3/node_modules/tsx/node_modules:/home/joelsgc/wall-e/rpi/~/.local/share/pnpm/global/5/.pnpm/tsx@4.22.3/node_modules:~/.local/share/pnpm/global/5/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/global/5/.pnpm/tsx@4.22.3/node_modules/tsx/dist/cli.mjs" "$@"
else
  exec node  "$basedir/global/5/.pnpm/tsx@4.22.3/node_modules/tsx/dist/cli.mjs" "$@"
fi
